name: Coin Price dev

on:
  push:
    branches: ["development"]
    paths-ignore:
      - README.md
      - Design/**
      - Documents/**
      - Meeting minutes/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Docker
        shell: pwsh
        run: |
          if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
            Write-Host "Docker not found. Installing Docker..."
            # Thực hiện cài đặt Docker cho Windows (nếu cần)
            Invoke-WebRequest -Uri https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe -OutFile DockerInstaller.exe
            Start-Process -FilePath DockerInstaller.exe -ArgumentList "install" -Wait
          } else {
            Write-Host "Docker already installed"
          }
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_ACCESS_USER }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_HUB_ACCESS_USER }}/coin-price .
          docker push ${{ secrets.DOCKER_HUB_ACCESS_USER }}/coin-price
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Pull Docker image
        run: |
          docker stop coin-price || true 
          docker rm coin-price || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/coin-price:latest
          docker run -d -p 3000:3000 --name coin-price ${{ secrets.DOCKERHUB_USERNAME }}/coin-price:latest
